best_match_model: xvlm
blip_half_precision: true
blip_v2_model_type: blip2-flan-t5-xxl
cached_codex_path: ''
clear_cache: false
codex:
  best_of: 1
  max_tokens: 512
  model: gpt-3.5-turbo
  prompt: ./prompts/chatapi.prompt
  temperature: 0.0
crop_larger_margin: true
dataset:
  batch_size: 20
  data_path: data
  dataset_name: MyDataset
  max_samples: null
  split: ''
  start_sample: 0
detect_thresholds:
  glip: 0.5
  maskrcnn: 0.8
  owlvit: 0.1
execute_code: false
fixed_code_file: ./prompts/fixed_code/blip2.prompt
glip:
  model_size: tiny
gpt3:
  guess_prompt: ./prompts/gpt3/gpt3_process_guess.txt
  model: text-davinci-003
  n_votes: 1
  qa_prompt: ./prompts/gpt3/gpt3_qa.txt
  temperature: 0.0
load_models:
  blip: true
  clip: false
  codellama: false
  codex: false
  depth: false
  glip: true
  gpt3_general: true
  gpt3_qa: true
  maskrcnn: false
  owlvit: false
  saliency: false
  tcl: false
  xvlm: false
log_every: 20
multiprocessing: false
path_pretrained_models: ./pretrained_models
ratio_box_area_to_image_area: 0.0
results_dir: ./results/
save: true
save_new_results: true
use_cache: true
use_cached_codex: false
use_fixed_code: false
verify_property:
  model: xvlm
  thresh_clip: 0.6
  thresh_tcl: 0.25
  thresh_xvlm: 0.6
wandb: false
